FROM python:3.12-slim

# Set working directory
WORKDIR /app

COPY backend/requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_sm

# Copy application code
COPY backend/ /app/

# Expose the port Sanic runs on
EXPOSE 1234

# Run the application
CMD ["python", "-m", "app"]